### ISSUE TITLE
Adicionar a plataforma Scrimba (Feature)

### ISSUE THREAD

**Issue by edu-correia** [perifacode/conteudo-gratuito#115]
Olá, eu gostaria de recomendar a plataforma [Scrimba](https://scrimba.com/), é uma plataforma tanto com conteúdos grátis como pagos, é em inglês, porém são cursos excelentes em diversas áreas da programação, mas o principal deles é o método de ensino, o Scrimba tem uma plataforma de ensino **FANTÁSTICA**, é como se você estivesse em uma sala de aula e o professor estivesse ensinando no seu computador.

**Comment by dominguetigs** [comment]
@eduardo-ehsc O `Scrimba` está sendo adicionado no PR #131 além de outros.
