### ISSUE TITLE
sugestão na estrutura do documento

### ISSUE THREAD

**Issue by sswellington** [perifacode/conteudo-gratuito#38]
O documento README.md, especificamente a tabela pode ser retirar a tupla link é juntar com a descrição.
Por exemplo, antes:
| Descrição      | Tipo (Curso, Livro, etc)           | Certificado | Idioma | Link  |
| ------------- |:-------------:| :-----:| :-----:|:-----:|
| Amanda Vilela | Youtube | Não | PT-BR | https://www.youtube.com/channel/UCBHuWBJdB8HSh3_ZLwPq9_w |
| Balta.io | Cursos | Não | PT-BR | https://balta.io/cursos | 

Depois:

| Descrição      | Tipo (Curso, Livro, etc)           | Certificado | Idioma |
| ------------- |:-------------:| :-----:| :-----:|
| [Amanda Vilela](https://www.youtube.com/channel/UCBHuWBJdB8HSh3_ZLwPq9_w) | Youtube | Não | PT-BR |  |
| [Balta.io](https://balta.io/cursos) | Cursos | Não | PT-BR |  

Por fim, a tupla tipo tem aumentado, portanto sugiro divido-lo em arquivos.
Logo, o arquivo README terá um link para cada tipo.

**Comment by jos3s** [comment]
Fiz essas alterações espero que eles aceitem o pr[#40](https://github.com/perifacode/conteudo-gratuito/pull/40)

**Comment by sswellington** [comment]
> Fiz essas alterações espero que eles aceitem o pr[#40](https://github.com/perifacode/conteudo-gratuito/pull/40)

As mudanças geraram conflitos, tenta corrigir depois.

**Comment by gitlherme** [comment]
Valeu, pessoal!

O PR foi aceito, os conflitos arrumados e já está no README.md do projeto!

Por isso, vou fechando essa issue. Qualquer coisa abrimos uma nova 😄
