### ISSUE TITLE
Melhorar a seção de Contribuintes do projeto

### ISSUE THREAD

**Issue by jos3s** [perifacode/conteudo-gratuito#41]
Existe um bot aqui para o Github cria uma tabela de contribuidores de um repoistório, é [All Contributors](https://allcontributors.org/). Seria interessante utilizar para evitar de editar a lista manualmente

**Comment by jamessom** [comment]
Seria bem bacana mesmo.

**Comment by sswellington** [comment]
O próprio git mostra os contribuidores automaticamente. 
Portanto, desnecessário ficar adicionando todos que contribuem

**Comment by jos3s** [comment]
> O próprio git mostra os contribuidores automaticamente. 
> Portanto, desnecessário ficar adicionando todos que contribuem

Mostra mas não de um jeito muito amigável, o que eu indiquei é gerado automaticamente e fica no readme, o que incentiva as contribuições e mostra em destaque as pessoas engajadas no projeto

**Comment by gitlherme** [comment]
Opa, ótima ideia pessoal!

Vou dar uma olhadinha nesse bot e colocar ele aqui :D

**Comment by gitlherme** [comment]
Adicionado na issue #84, pessoal!
Os próximos contribuidores serão inseridos na hora que o PR for aceito 😊

Valeu pelas dicas!
Tamo junto 🖤
